name: Auto-Merge on Green Checks

on:
  check_suite:
    types: [completed]
  workflow_run:
    workflows: ["Preview Check"]
    types: [completed]

jobs:
  auto-merge:
    name: Auto-merge when checks pass
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' ||
      github.event_name == 'check_suite' && github.event.check_suite.conclusion == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PR for commit
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pulls } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });

            const pr = pulls.find(p => p.head.sha === context.sha);
            if (pr) {
              return pr.number;
            }
            return null;

      - name: Check if all required checks passed
        if: steps.pr.outputs.result
        id: check-status
        uses: actions/github-script@v7
        with:
          script: |
            const pr_number = ${{ steps.pr.outputs.result }};

            // Get PR details
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            });

            // Get all checks for the head SHA
            const { data: checkRuns } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.head.sha
            });

            // Check if Preview Check passed
            const previewCheck = checkRuns.check_runs.find(run =>
              run.name === 'Build and Lint'
            );

            // Get statuses (for Vercel)
            const { data: statuses } = await github.rest.repos.getCombinedStatusForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.head.sha
            });

            // Check if Vercel Preview passed
            const vercelCheck = statuses.statuses.find(status =>
              status.context === 'Vercel'
            );

            const allChecksPassed =
              previewCheck?.conclusion === 'success' &&
              vercelCheck?.state === 'success';

            return allChecksPassed;

      - name: Enable auto-merge
        if: steps.check-status.outputs.result == 'true'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.pr.outputs.result }}
          merge-method: squash