name: Nightly Blog

on:
  schedule:
    # Run at 04:43 UTC every night
    - cron: "43 4 * * *"
  workflow_dispatch: # Allow manual triggering for testing

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-posts:
    name: Generate Blog Posts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable corepack for pnpm
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate blog posts
        run: pnpm run generate:posts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL || 'gpt-4o-mini' }}

      - name: Detect blog changes
        id: blog_changes
        run: |
          CHANGED=$(git status --porcelain -- content/blog src/data/.posts_history.json src/data/keywords.json | wc -l)
          echo "changed=$CHANGED" >> $GITHUB_OUTPUT

          if [[ $CHANGED -gt 0 ]]; then
            echo "✅ Blog content changes detected:"
            git status --porcelain -- content/blog src/data/.posts_history.json src/data/keywords.json
          else
            echo "ℹ️ No blog content changes (all topics may be recently used)"
          fi

      - name: Create Pull Request
        if: ${{ steps.blog_changes.outputs.changed != '0' }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_FOR_AUTOMATION || secrets.GITHUB_TOKEN }}
          commit-message: "chore(blog): nightly posts"
          title: "chore(blog): nightly posts"
          body: |
            ## 🤖 Automated Blog Generation

            This PR contains automatically generated blog posts from the nightly workflow.

            ### Features
            - LRU topic rotation (avoids reusing topics within 7 days)
            - Evergreen backfill pool of 30 high-value topics
            - Retry mechanism with fallback templates
            - Posts generated to `content/blog/` directory

            ### Review Checklist
            - [ ] Content quality and formatting look good
            - [ ] Internal links are working correctly
            - [ ] No duplicate topics

            ---
            *Generated by the nightly blog workflow using PAT for automation*
          branch: "automation/nightly-blog"
          delete-branch: true
          labels: |
            automation
            blog
            content

      - name: Log workflow result
        if: always()
        run: |
          if [[ "${{ steps.blog_changes.outputs.changed }}" != "0" ]]; then
            echo "✅ Workflow completed: PR created with new blog posts"
          else
            echo "ℹ️ Workflow completed: No new content generated (topics may be recently used)"
          fi