name: Nightly Blog

on:
  schedule:
    # Run at 04:43 UTC every night
    - cron: "43 4 * * *"
  workflow_dispatch: # Allow manual triggering for testing

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-posts:
    name: Generate Blog Posts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable corepack for pnpm
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate blog posts
        run: pnpm run generate:posts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL || 'gpt-4o-mini' }}

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git diff --name-only -- src/content/blog src/data/keywords.json src/data/.posts_history.json 2>/dev/null) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "✅ New blog posts were generated"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "ℹ️  No new blog posts generated (all topics may be recently used)"
          fi

      - name: QA Guard - Verify content generation
        if: steps.check_changes.outputs.changes == 'false'
        run: |
          if [[ -n "${{ secrets.OPENAI_API_KEY }}" ]]; then
            echo "⚠️  WARNING: Generator ran but produced no new content"
            echo "This might indicate all topics were recently used or a generation issue"
          else
            echo "ℹ️  Skipped: No OPENAI_API_KEY configured"
          fi

      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(blog): nightly +5 posts"
          title: "chore(blog): nightly +5 posts"
          body: |
            ## 🤖 Automated Blog Generation

            This PR contains automatically generated blog posts from the nightly workflow.

            ### Changes
            - Generated up to 5 new blog posts
            - Updated topic history for LRU rotation
            - Posts use either API generation or fallback templates

            ### Review Checklist
            - [ ] Content quality and formatting look good
            - [ ] Internal links are working
            - [ ] No duplicate topics

            ---
            *Generated by the nightly blog workflow*
          branch: "automation/nightly-blog"
          delete-branch: true
          labels: |
            automation
            blog
            content
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log workflow result
        if: always()
        run: |
          if [[ "${{ steps.check_changes.outputs.changes }}" == "true" ]]; then
            echo "✅ Workflow completed: PR created with new blog posts"
          else
            echo "ℹ️  Workflow completed: No new content generated"
          fi