name: Nightly Answers

on:
  schedule:
    - cron: "19 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-answers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - name: Generate answers
        run: pnpm run generate:answers
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL || 'gpt-4o-mini' }}
      - name: Commit & push
        run: |
          if [[ -n "$(git status --porcelain src/data/answers.json)" ]]; then
            git config user.name  "automation-bot"
            git config user.email "automation@users.noreply.github.com"
            git add src/data/answers.json
            git commit -m "chore(answers): nightly AEO Q&As"
            git push https://x-access-token:${{ secrets.PAT_FOR_AUTOMATION }}@github.com/${{ github.repository }} HEAD:main
          else
            echo "No changes to commit."
          fi