name: Preview Check

on:
  pull_request:
    branches: [main]

jobs:
  build-and-lint:
    name: Build and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Enable corepack for pnpm
        run: corepack enable

      - name: Log pnpm version
        run: pnpm -v

      - name: Install dependencies (frozen lockfile)
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm run build

      - name: Run linter
        run: pnpm run lint